version: '3.8'

services:
    dev:
        container_name: text_mining_frontend_dev
        image: text_mining_frontend_dev:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 4200:80
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
