version: '3'

services:
    dev:
        container_name: reports-microservice-dev
        image: reports-microservice:dev
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped

    prod:
        container_name: reports-microservice-prod
        image: reports-microservice:prod
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        ports:
            - 3001:3001
        restart: unless-stopped
