version: '3'

services:
    dev:
        container_name: reports-microservice
        image: reports-microservice:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        
