version: '3'

services:
    dev:
        container_name: reports-microservice
        image: reports-microservice:1.0.0
        environment:
          - PORT=${PORT}
          - RABBITMQ_URL=${RABBITMQ_URL}
          - CLARISA_HOST=${CLARISA_HOST}
          - CLARISA_MIS=${CLARISA_MIS}
          - CLARISA_MIS_ENV=${CLARISA_MIS_ENV}
          - CLARISA_LOGIN=${CLARISA_LOGIN}
          - CLARISA_PASSWORD=${CLARISA_PASSWORD}
          - IS_PRODUCTION=${IS_PRODUCTION}
          - SEE_ALL_LOGS=${SEE_ALL_LOGS}
          - QUEUE_NAME=${QUEUE_NAME}
          - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
          - AWS_REGION=${AWS_REGION}
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start
        ports:
            - 3001:3001
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        
