name: Trigger Jenkins Job AI Text Mining Microservice

on:
  push:
    branches:
      - "dev-mining" # Only on push to main-mining
  pull_request:
    branches:
      - "dev-mining" # Only on PR to main-mining
  workflow_dispatch: # Allows manual trigger if needed

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Build Jenkins URL
      - name: Build Jenkins URL
        run: |
          JENKINS_URL="https://automation.prms.cgiar.org/job/ai-text-mining-microservice/build"
          echo "Jenkins job URL: $JENKINS_URL"
          echo "JENKINS_URL=${JENKINS_URL}" >> $GITHUB_ENV

      # Step 2: Trigger Jenkins Job
      - name: Trigger Jenkins Job
        run: |
          curl -X POST ${{ env.JENKINS_URL }} --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }}
        env:
          JENKINS_URL: ${{ env.JENKINS_URL }}
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
