name: Trigger Jenkins Job AUTH Microservice

on:
  push:
    branches:
      - "main-auth"
      - "dev-auth"
  pull_request:
    branches:
      - "main-auth"
      - "dev-auth"
  workflow_dispatch:

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Build Jenkins URL
      - name: Build Jenkins URL
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}  # Remove 'refs/heads/' from GITHUB_REF
          JENKINS_URL="https://automation.prms.cgiar.org/job/auth-microservice-${BRANCH_NAME}/build"
          echo "Jenkins job URL: $JENKINS_URL"
          echo "JENKINS_URL=${JENKINS_URL}" >> $GITHUB_ENV

      # Step 2: Trigger Jenkins Job
      - name: Trigger Jenkins Job
        run: |
          curl -X POST ${{ env.JENKINS_URL }} --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }}
        env:
          JENKINS_URL: ${{ env.JENKINS_URL }}
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
