name: Trigger Jenkins Job FileManager Swarm

on:
  push:
    branches:
      - "main-reports" # Only on push to main-reports
  pull_request:
    branches:
      - "main-reports" # Only on PR to main-reports

jobs:
  trigger-job:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Define Jenkins URL
      - name: Set Jenkins URL
        run: |
          JENKINS_URL="https://automation.prms.cgiar.org/job/microservice-files-management-swarm-prod/build"
          echo "Jenkins job URL is: $JENKINS_URL"
          echo "JENKINS_URL=${JENKINS_URL}" >> $GITHUB_ENV

      # Step 2: Trigger job in Jenkins
      - name: Trigger Jenkins Job
        run: |
          curl -X POST ${{ env.JENKINS_URL }} --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }}
        env:
          JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
